apps/almacenes/urls.py
from django.urls import path
from apps.almacenes.views import *

app_name = 'almacenes'

urlpatterns = [
    path('crear_almacen/', crear_almacen_view, name='crear_almacen'),
    path('consultar_almacenes/', consultar_almacenes_view, name='consultar_almacenes'),
    path('modificar_almacen/<int:id>', modificar_almacen_view, name='modificar_almacen'),
    path('eliminar_almacen/<int:id>', eliminar_almacen_view, name='eliminar_almacen'),
]

apps/carritos/urls.py
from django.urls import path
from apps.carritos.views import *
from django.contrib.auth.views import *

app_name = 'carritos'

urlpatterns = [
    path('addToCart/<str:codigo>', addToCart_view, name='addToCart'),
    path('carrito', consultarCarrito_view, name='carrito'),
    path('carrito/<int:id>', eliminarCarrito_view, name='eliminar'),
    path('sumarCantidad/<int:id>', cambiarCantidad_view, name='modificar'),
]

apps/productos/urls.py
from django.urls import path
from .views import *

app_name = 'productos'

urlpatterns=[
    path('registrar/', registrar_view, name = 'registrar'),
    path('consultar/', consultarProdutos_view, name = 'consultar'),
    path('subcategoria/<int:subcategoria_id>', consultarPorSubcategoria_view, name = 'consultarPorSubcategoria'),
    path('categoria/<int:categoria_id>', consultarPorCategoria_view, name = 'consultarPorCategoria'),
    path('producto/<str:codigo>', consultarProducto_view, name = 'consultarProducto'),
    path('modificar/<str:codigo>', modificarProductos_view, name = 'modificar'),
    path('eliminar/<str:codigo>', eliminarProducto_view, name = 'eliminar'),
    path('detalle/<int:id>', eliminarDetalle_view, name = 'eliminar_detalle'),
    path('descuentos/', productosDescuento_view, name = 'descuentos'),
]

madlab/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.pages import views

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cliente/', include('apps.clientes.urls', namespace = 'clientes')),
    path('gerente/', include('apps.usuarios.urls', namespace = 'gerentes')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    path('categorias/', include('apps.categorias.urls', namespace='categorias')),
    path('subcategorias/', include('apps.subcategorias.urls', namespace='subcategorias')),
    path('almacenes/', include('apps.almacenes.urls', namespace='almacenes')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('descuentos/', include('apps.descuentos.urls', namespace = 'descuentos')),
    path('carritos/', include('apps.carritos.urls', namespace = 'carritos')),
    path('reportes/', include('apps.reportes.urls', namespace = 'reportes')),
    path('facturas/', include('apps.facturas.urls', namespace = 'facturas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/almacenes/models.py
from django.db import models

# Create your models here.


class Almacen(models.Model):
    # Ciudades
    CALI = 'Cali'
    BOGOTA = 'Bogota'
    MEDELLIN = 'Medellin'
    BARRANQUILLA = 'Barranquilla'
    CARTAGENA = 'Cartagena'
    CUCUTA = 'Cucuta'
    IBAGUE = 'Ibague'
    PASTO = 'Pasto'

    CIUDAD_CHOICES = {
        (CALI, 'Cali'),
        (BOGOTA, 'Bogota'),
        (MEDELLIN, 'Medellin'),
        (BARRANQUILLA, 'Barranquilla'),
        (CARTAGENA, 'Cartagena'),
        (CUCUTA, 'Cucuta'),
        (IBAGUE, 'Ibague'),
        (PASTO, 'Pasto'),
    }

    ciudad = models.CharField(
        choices=CIUDAD_CHOICES,
        max_length=20,
        blank=True,
        unique=True
    )

    direccion = models.CharField(max_length=30)

    producto = models.ManyToManyField(
        'productos.Producto', blank=True, through='inventario.Inventario')

    def __str__(self):
        return self.ciudad

apps/almacenes/forms.py
from django import forms
from .models import Almacen

class FormularioCreacionAlmacen(forms.ModelForm):
    class Meta():
        model = Almacen
        fields = ('ciudad', 'direccion')

class FormularioCiudad(forms.ModelForm):
    #ciudad = forms.ModelChoiceField(queryset = Almacen.objects.all())
    
    class Meta():
        model = Almacen
        fields = ('ciudad',)

apps/almacenes/views.py
from django.shortcuts import render, redirect
from .forms import FormularioCreacionAlmacen
from django.contrib import messages
from .models import Almacen
from apps.inventario.models import Inventario
from apps.categorias.models import Categoria
from apps.productos.models import Producto

# Create your views here.
def crear_almacen_view(request):
    categorias = Categoria.objects.all()
    if request.method == 'POST':
        form = FormularioCreacionAlmacen(request.POST)
        if form.is_valid():
            almacen = form.save()
            productos = Producto.objects.all()
            for producto in productos:
                inventario = Inventario()
                inventario.almacen = almacen
                inventario.producto = producto
                inventario.cantidad = 1
                inventario.save()
            messages.success(request, 'Almacen registrado existosamente')
            redirect('almacenes:crear_almacen')
    else:
        form = FormularioCreacionAlmacen()

    return render(request, 'almacenes/registro.html', {'form': form, 'categorias': categorias})

def consultar_almacenes_view(request):
    categorias = Categoria.objects.all()
    almacenes = Almacen.objects.all()
    return render(request, 'almacenes/consultar.html', {'almacenes': almacenes, 'categorias': categorias})


def modificar_almacen_view(request, id):
    categorias = Categoria.objects.all()
    almacen = Almacen.objects.get(id=id)
    if request.method == 'GET':
        form = FormularioCreacionAlmacen(instance = almacen)
    else:
        form = FormularioCreacionAlmacen(request.POST, instance = almacen)
        if form.is_valid():
            form.save()
            messages.success(request, 'Almacen modificado exitosamente')
        return redirect('almacenes:consultar_almacenes')

    return render(request, 'almacenes/modificar.html', {'form': form, 'categorias': categorias})

def eliminar_almacen_view(request, id):
    almacen = Almacen.objects.filter(pk = id).delete()
    messages.success(request, 'Almacen eliminado exitosamente')
    return redirect('almacenes:consultar_almacenes')

apps/almacenes/templates/almacenes/consultar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Consultar almacenes
{% endblock titulo%}

{% block titulo_contenido%}
Almacenes
{% endblock titulo_contenido%}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido %}
<!--filas donde se contendran 3 widgets-->
<div class="box box-danger" style="padding: 10px">
    {% for almacen in almacenes %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-md-6">
            <div class="box box-solid box-danger">
                <div class="box-header">
                    <h3 class="box-title">{{almacen.ciudad}}</h3>
                    <div class="box-tools pull-right">
                        <a href="{% url 'almacenes:modificar_almacen' almacen.id %}">
                            <button class="btn btn-danger btn-sm"><i class="fa fa-pencil"></i></button>
                        </a>
                        <!--BOTON EL CUAL INVOCA AL MODAL-->
                        <a data-toggle="modal" data-target="#compose-modal_{{almacen.ciudad}}">
                            <button class="btn btn-danger btn-sm">
                                <i class="fa fa-times"></i></i>
                            </button>
                        </a>
                        <!--/BOTON EL CUAL INVOCA AL MODAL-->
                    </div>
                    <!--EL MODAL-->
                    <div class="modal fade" id="compose-modal_{{almacen.ciudad}}" tabindex="-1" role="dialog"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"
                                        aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">¿Esta seguro que desea eliminar este almacen?</h4>
                                </div>

                                <div class="modal-footer clearfix">

                                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                            class="fa fa-times"></i>Cancelar</button>
                                    <a href="{% url 'almacenes:eliminar_almacen' almacen.id %}">
                                        <button type="submit" class="btn btn-primary pull-left"> Si, estoy
                                            seguro</button>
                                    </a>
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                    <!--/EL MODAL-->
                </div>
                <div class="box-body">
                    <div class="contenido">
                        <div><b>ID:</b> {{almacen.id}}</div>
                        <div><b>Direccion:</b> {{almacen.direccion}}</div>
                    </div>
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Inventario</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body no-padding">
                            <table class="table table-striped">
                                <tr>
                                    <th>Producto</th>
                                    <th>Cantidad</th>
                                    <th>Acciones</th>
                                </tr>
                                {% for inventario in almacen.inventarios.all %}
                                <tr>
                                    <td>{{ inventario.producto }}</td>
                                    <td>{{ inventario.cantidad }}</td>

                                    <td>
                                        <!--Boton-->
                                        <a data-toggle="modal" data-target="#compose-modal_{{inventario.id}}">
                                            <button class="btn btn-danger btn-sm">
                                                <i class="fa fa-pencil"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                                <div class="modal fade" id="compose-modal_{{inventario.id}}" tabindex="-1" role="dialog"
                                    aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-hidden="true">&times;</button>
                                                <h4 class="modal-title">ACTUALIZAR CANTIDAD DEL PRODUCTO EN EL ALMACEN
                                                </h4>
                                            </div>
                                            <form method="post" enctype="multipart/form-data"
                                                action="{% url 'inventario:modificar' inventario.id  %}">
                                                <div class="modal-body">
                                                    {% csrf_token %}
                                                    <div class="input-group">
                                                        <h5><b>Cantidad : </b><input style="width: 100px;" type="number"
                                                                id="cantidad_{{inventario.id}}" name="cantidad"
                                                                value="{{inventario.cantidad}}">
                                                        </h5>
                                                    </div>

                                                </div>
                                                <div class="modal-footer clearfix">

                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                                                        <i class="fa fa-times"></i>Cancelar
                                                    </button>
                                                    <button type="submit" class="btn btn-primary pull-left">
                                                        Actualizar
                                                    </button>
                                                </div>
                                            </form>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->
                                {% endfor %}
                            </table>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <!--widgets-->
        </div>
        {% if forloop.counter|divisibleby:2 %}</div>
    <div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}

    {% endfor %}
    <!--filas-->

    <!--widget-->
</div>
{% endblock contenido%}

apps/almacenes/templates/almacenes/modificar.html
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block titulo %}
Modificar almacen
{% endblock titulo%}

{% block titulo_contenido%}
Modificar almacen
{% endblock titulo_contenido%}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido%}
<div class="box box-danger" style="padding: 10px">
    <form method="POST">
        <div>
            {% csrf_token %}
            {% bootstrap_form form %}
        </div>
        <div>
            <button type="submit">Modificar</button>
        </div>
    </form>
</div>
{% endblock contenido%}

apps/almacenes/templates/almacenes/registro.html
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block titulo %}
Registrar categoria
{% endblock titulo%}

{% block titulo_contenido%}
Registrar categoria
{% endblock titulo_contenido%}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido%}
<div class="box box-danger" style="padding: 10px">
    <form method="POST">
        <div>
            {% csrf_token %}
            {% bootstrap_form form %}
        </div>
        <div>
            <button type="submit">Agregar</button>
        </div>
    </form>
</div>
{% endblock contenido%}