apps/carritos/urls.py
from django.urls import path
from apps.carritos.views import *
from django.contrib.auth.views import *

app_name = 'carritos'

urlpatterns = [
    path('addToCart/<str:codigo>', addToCart_view, name='addToCart'),
    path('carrito', consultarCarrito_view, name='carrito'),
    path('carrito/<int:id>', eliminarCarrito_view, name='eliminar'),
    path('sumarCantidad/<int:id>', cambiarCantidad_view, name='modificar'),
]

apps/facturas/urls.py
from django.urls import path
from apps.facturas.views import *

app_name = 'facturas'

urlpatterns = [
    path('pago/<str:ciudad>', pago_view, name='pago'),
    path('compras/<str:numero_documento>', compras_view, name='compras'),
]

apps/productos/urls.py
from django.urls import path
from .views import *

app_name = 'productos'

urlpatterns=[
    path('registrar/', registrar_view, name = 'registrar'),
    path('consultar/', consultarProdutos_view, name = 'consultar'),
    path('subcategoria/<int:subcategoria_id>', consultarPorSubcategoria_view, name = 'consultarPorSubcategoria'),
    path('categoria/<int:categoria_id>', consultarPorCategoria_view, name = 'consultarPorCategoria'),
    path('producto/<str:codigo>', consultarProducto_view, name = 'consultarProducto'),
    path('modificar/<str:codigo>', modificarProductos_view, name = 'modificar'),
    path('eliminar/<str:codigo>', eliminarProducto_view, name = 'eliminar'),
    path('detalle/<int:id>', eliminarDetalle_view, name = 'eliminar_detalle'),
    path('descuentos/', productosDescuento_view, name = 'descuentos'),
]

madlab/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.pages import views

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cliente/', include('apps.clientes.urls', namespace = 'clientes')),
    path('gerente/', include('apps.usuarios.urls', namespace = 'gerentes')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    path('categorias/', include('apps.categorias.urls', namespace='categorias')),
    path('subcategorias/', include('apps.subcategorias.urls', namespace='subcategorias')),
    path('almacenes/', include('apps.almacenes.urls', namespace='almacenes')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('descuentos/', include('apps.descuentos.urls', namespace = 'descuentos')),
    path('carritos/', include('apps.carritos.urls', namespace = 'carritos')),
    path('reportes/', include('apps.reportes.urls', namespace = 'reportes')),
    path('facturas/', include('apps.facturas.urls', namespace = 'facturas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/carritos/models.py
from django.db import models

# Create your models here.
class Carrito(models.Model):
    cantidad = models.IntegerField()
    producto = models.ForeignKey('productos.Producto', on_delete=models.CASCADE)
    cliente = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE)

apps/carritos/forms.py
from django import forms
from .models import Carrito

class FormularioCarrito(forms.ModelForm):
    class Meta():
        model = Carrito
        fields = ('cantidad',)

apps/carritos/views.py
from django.shortcuts import render, redirect
from .models import Carrito
from .forms  import FormularioCarrito
from apps.almacenes.forms import FormularioCiudad
from apps.productos.models import Producto
from apps.usuarios.models import Usuario
from apps.almacenes.models import Almacen
from apps.categorias.models import Categoria
from apps.inventario.models import Inventario
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q


# Create your views here.
def addToCart_view(request, codigo):
    producto = Producto.objects.get(codigo = codigo)
    cliente = request.user
    producto_exist = (Carrito.objects.filter(cliente = cliente, producto = producto).count() > 0)
    if producto_exist:
        messages.warning(request, 'El producto ya se encuentra en el carrito')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        try:
            almacen = Almacen.objects.get(ciudad=ciudad)
            inventario = Inventario.objects.get(almacen=almacen, producto=producto)
            cantInventario = int(inventario.cantidad)
            if cantInventario == 0:
                messages.warning(request, 'No quedan unidades de este producto donde se encuentra localizado')
            else: 
                carrito = Carrito()
                carrito.cantidad = 1
                carrito.producto = producto
                carrito.cliente = cliente
                carrito.save()
                messages.success(request, 'Producto añadido exitosamente')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except:
            primer_almacen = Almacen.objects.all()[0]
            inventario = Inventario.objects.get(almacen=primer_almacen, producto=producto)
            cantInventario = int(inventario.cantidad)
            if cantInventario == 0:
                messages.warning(request, 'No quedan unidades de este producto donde se encuentra localizado')
            else: 
                carrito = Carrito()
                carrito.cantidad = 1
                carrito.producto = producto
                carrito.cliente = cliente
                carrito.save()
                messages.success(request, 'Producto añadido exitosamente')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def consultarCarrito_view(request):
    categorias = Categoria.objects.all()
    form_ciudades = FormularioCiudad()

    #CARRITO
    if not request.user.is_authenticated:
        carritos = None
    else:
        cliente = request.user
        carritos = Carrito.objects.filter(cliente = cliente)

    #CAMBIAR CIUDAD
    global ciudad
    if request.method == 'POST':
        form = FormularioCiudad(request.POST)
        almacen = form.data['ciudad']
        almacen_exist = (Almacen.objects.filter(ciudad = almacen).count() > 0)
        
        if almacen_exist:
            ciudad = almacen
            messages.success(request, 'Usted cambió de locación, ahora se encuentra en ' + almacen)
            for carrito in carritos:
                producto = carrito.producto
                
                almacen = Almacen.objects.get(ciudad=ciudad)
                inventario = Inventario.objects.get(almacen=almacen, producto=producto)
                cantInventario = int(inventario.cantidad)
                if cantInventario == 0:
                    carrito.delete()
                else:
                    carrito.cantidad = 1
                    carrito.save()
        else:
            messages.warning(request, 'Lo sentimos, no tenemos almacenes disponibles en ' + almacen )
        
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = FormularioCiudad()
    
    queryset = request.GET.get("buscar")
    primer_almacen = Almacen.objects.all()[0].ciudad
    #BARRA BUSQUEDA
    if queryset:
        productos = Producto.objects.filter(
            Q(nombre__icontains = queryset) |
            Q(descripcion__icontains = queryset)|
            Q(subcategoria__nombre__icontains = queryset) |
            Q(subcategoria__categoria__nombre__icontains = queryset)
        ).distinct()
        return render(request, 'home.html', {'productos':productos, 'categorias': categorias, 'carritos':carritos})
    else:
        try:
            return render(request, 'carritos/carrito.html', {'categorias': categorias, 'carritos':carritos, 'form_ciudades': form_ciudades, 'ciudad': ciudad})
        except:
            return render(request, 'carritos/carrito.html', {'categorias': categorias, 'carritos':carritos, 'form_ciudades': form_ciudades, 'ciudad': primer_almacen})

def eliminarCarrito_view(request, id):
    carrito = Carrito.objects.get(pk=id)
    carrito.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def cambiarCantidad_view(request, id):
    cantidad = int(request.POST["cantidad"])
    carrito = Carrito.objects.get(id=id)
    producto = carrito.producto
    try: 
        almacen = Almacen.objects.get(ciudad=ciudad)
        inventario = Inventario.objects.get(almacen=almacen, producto=producto)
        cantInventario = int(inventario.cantidad)

        if cantidad > 0 and cantidad <= cantInventario:
            carrito.cantidad = cantidad
            carrito.save()
        else:
            messages.warning(request, 'Solo existen ' + str(cantInventario) + ' unidades de este producto, por favor proporcione una cantidad valida')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except:      
        primer_almacen = Almacen.objects.all()[0]
        inventario = Inventario.objects.get(almacen=primer_almacen, producto=producto)
        cantInventario = int(inventario.cantidad)

        if cantidad > 0 and cantidad <= cantInventario:
            carrito.cantidad = cantidad
            carrito.save()
        else:
            messages.warning(request, 'Solo existen ' + str(cantInventario) + ' unidades de este producto, por favor proporcione una cantidad valida')

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    


    

apps/carritos/templates/carritos/carrito.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block titulo %}
Carrito de compras
{% endblock titulo%}

{% block titulo_contenido%}
Carrito de compras
{% endblock titulo_contenido%}

{% block carrito %}
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <image src="{% static 'carrito.png'%}" heigth="20" width="20"></image>

        <span class="label label-warning">{{ carritos|length }}</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header" style="color: black"><b>Tienes {{ carritos|length }} producto(s) en tu carrito</b>
        </li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                {% for carrito in carritos %}
                <li>
                    <a href="{% url 'productos:consultarProducto' carrito.producto.codigo %}" style="color: black">
                        <div class="pull-left">
                            <img src="{{ MEDIA_URL }}{{carrito.producto.imagen}}" width="75px">
                        </div>
                        <h4 style="color: black">{{ carrito.producto.nombre }}</h4>
                        <p id="precio" type="number">
                            $ {{ carrito.producto.oferta }}
                        </p>
                        <p id="cantidad" type="number">
                            Cantidad : {{ carrito.cantidad }}
                        </p>
                    </a>

                </li>
                {% endfor %}
            </ul>
        </li>
        <li class="footer"><a href="{% url 'carritos:carrito' %}" style="color: black">Ir al carrito</a></li>
    </ul>
</li>
{% endblock carrito %}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido%}
<script>
    var total = 0;
</script>
<div class="row">
    <div class="col-md-9">
        <div class="box box-danger" style="padding: 10px">
            {% for carrito in carritos %}
            <div class="row">
                <div class="col-md-3">
                    <div>
                        <img src="{{ MEDIA_URL }}{{carrito.producto.imagen}}">
                    </div>

                </div>
                <div class="col-md-5">
                    <div>
                        <h3>{{carrito.producto.nombre}}</h3>
                        <h5 class="text-muted">{{carrito.producto.subcategoria.categoria.nombre}} /
                            {{carrito.producto.subcategoria.nombre}}</h5>
                        <h5 class="text-muted">Codigo artículo: {{carrito.producto.codigo}}</h5>
                        <h5 class="text-muted">Vendido y entregado por {{carrito.producto.fabricante}}</h5>
                        <h5 class="text-muted"><b>IVA : </b> {{carrito.producto.iva}} %</h5>
                    </div>
                    <a href="{% url 'carritos:eliminar' carrito.id %}">
                        <button class="btn btn-warning btn-flat">Eliminar
                            producto</button>
                    </a>

                </div>
                <div class="col-md-4">
                    <div>

                        <div>
                            <h4><b>Precio unitario :
                                </b><span>{% if carrito.producto.oferta == carrito.producto.precio %}
                                    <b>$</b> {{carrito.producto.oferta}}
                                    {% else %}
                                    <b>$</b><strike>{{carrito.producto.precio}} </strike> {{carrito.producto.oferta}}
                            </h4>
                            {% endif %}
                            </span>
                        </div>
                        <h4><b>Precio : </b><b>$</b> <span id="precio_{{carrito.id}}">{{carrito.producto.oferta}}
                            </span></h4>
                        <h1 class="page-header"></h1>
                        <form method="post" enctype="multipart/form-data"
                            action="{% url 'carritos:modificar' carrito.id  %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <h5><b>Cantidad : </b><input style="width: 100%;" type="number"
                                        id="cantidad_{{carrito.id}}" name="cantidad" value="{{carrito.cantidad}}">
                                </h5>
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-warning btn-flat"><i
                                            class="fa fa-check"></i></button>
                                </span>
                            </div>
                        </form>

                        <h4><b>Subtotal : $ </b>
                            <span id="subtotal_{{carrito.id}}"></span>
                        </h4>
                        <script>
                            var precio = parseFloat(document.getElementById("precio_{{carrito.id}}").innerText);
                            var inputVal = document.getElementById("cantidad_{{carrito.id}}").value;
                            var y = (precio * inputVal);
                            total = (total + y)
                            document.getElementById("subtotal_{{carrito.id}}").innerHTML = y;

                        </script>
                    </div>
                </div>

            </div>
            <h1 class="page-header"></h1>
            {% endfor %}


        </div>
    </div>
    <div class="col-md-3">
        <div class="box box-danger" style="padding: 10px">
            <h1 class="page-header">Resumen carrito</h1>
            <div class="row">
                <div class="col-md-12">
                    <h3><i class="fa fa-map-marker"></i> Usted está en <b>{{ciudad}}</b></h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h4>Cambia tu ciudad : </h4>
                    <form method="post" enctype="multipart/form-data">
                        <div class="input-group">
                            {% csrf_token %}
                            {% bootstrap_form form_ciudades %}
                            <span class="input-group-btn" style="padding-top: 10px">
                                <button type="submit" class="btn btn-warning btn-flat"><i
                                        class="fa fa-check"></i></button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <h1 class="page-header"></h1>
            <div class="row">
                <div class="col-md-12">
                    <h5><b>Total : </b></h5>
                    <h3><b> $ </b>
                        <span id="total">xd</span>
                    </h3>
                    <h5 class="text-muted">IVA incluido</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">

                    <h1 class="page-header"></h1>
                    {% if ciudad == '-' or carritos|length == 0 %}
                    {% else %}
                    <a href="{% url 'facturas:pago' ciudad %}">
                        <button class="btn btn-warning btn-flat">Proceder al pago</button>
                    </a>
                    {% endif %}
                    <div style="padding-top: 7px">
                        <a href="{% url 'home' %}">
                            <button class="btn btn-danger btn-flat">Continuar comprando</button>
                        </a>
                    </div>
                </div>
            </div>
            <script>
                var iva = (total * 0.19)
                total = total + iva
                document.getElementById("total").innerHTML = total;
            </script>
        </div>
    </div>
</div>
{% endblock contenido%}