apps/carritos/urls.py
from django.urls import path
from apps.carritos.views import *
from django.contrib.auth.views import *

app_name = 'carritos'

urlpatterns = [
    path('addToCart/<str:codigo>', addToCart_view, name='addToCart'),
    path('carrito', consultarCarrito_view, name='carrito'),
    path('carrito/<int:id>', eliminarCarrito_view, name='eliminar'),
    path('sumarCantidad/<int:id>', cambiarCantidad_view, name='modificar'),
]

apps/clientes/urls.py
from django.urls import path
from apps.clientes.views import *
from django.contrib.auth.views import *

app_name = 'clientes'
urlpatterns=[
    path('registro/', registro_view, name = 'registro'),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('perfil/<str:numero_documento>', perfil_view, name = 'perfil'),
    path('change-password/', change_password, name = 'change_password'),
    path('eliminar-cuenta/<str:numero_documento>', eliminarCuenta_view, name = 'eliminar-cuenta'),
    path('consultar_clientes/', consultarClientes_view, name = 'consulta'),
    path('activar_cliente/<str:numero_documento>', activarCliente_view, name = 'activar-cuenta'),
]

apps/facturas/urls.py
from django.urls import path
from apps.facturas.views import *

app_name = 'facturas'

urlpatterns = [
    path('pago/<str:ciudad>', pago_view, name='pago'),
    path('compras/<str:numero_documento>', compras_view, name='compras'),
]

apps/productos/urls.py
from django.urls import path
from .views import *

app_name = 'productos'

urlpatterns=[
    path('registrar/', registrar_view, name = 'registrar'),
    path('consultar/', consultarProdutos_view, name = 'consultar'),
    path('subcategoria/<int:subcategoria_id>', consultarPorSubcategoria_view, name = 'consultarPorSubcategoria'),
    path('categoria/<int:categoria_id>', consultarPorCategoria_view, name = 'consultarPorCategoria'),
    path('producto/<str:codigo>', consultarProducto_view, name = 'consultarProducto'),
    path('modificar/<str:codigo>', modificarProductos_view, name = 'modificar'),
    path('eliminar/<str:codigo>', eliminarProducto_view, name = 'eliminar'),
    path('detalle/<int:id>', eliminarDetalle_view, name = 'eliminar_detalle'),
    path('descuentos/', productosDescuento_view, name = 'descuentos'),
]

madlab/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.pages import views

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cliente/', include('apps.clientes.urls', namespace = 'clientes')),
    path('gerente/', include('apps.usuarios.urls', namespace = 'gerentes')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    path('categorias/', include('apps.categorias.urls', namespace='categorias')),
    path('subcategorias/', include('apps.subcategorias.urls', namespace='subcategorias')),
    path('almacenes/', include('apps.almacenes.urls', namespace='almacenes')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('descuentos/', include('apps.descuentos.urls', namespace = 'descuentos')),
    path('carritos/', include('apps.carritos.urls', namespace = 'carritos')),
    path('reportes/', include('apps.reportes.urls', namespace = 'reportes')),
    path('facturas/', include('apps.facturas.urls', namespace = 'facturas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/clientes/models.py
from django.db import models
from apps.usuarios.models import Usuario
from django.conf import settings

# Create your models here.
class Cliente(Usuario):
    
    telefono = models.CharField(max_length = 10)
    direccion = models.CharField(max_length = 40)

apps/clientes/forms.py
from django import forms
from .models import Cliente
from ..usuarios.models import Usuario
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime



class FormularioRegistroCliente(UserCreationForm):
    def clean(self):
        cleaned_data = super(FormularioRegistroCliente, self).clean()
        fecha_nacimiento = cleaned_data.get('fecha_nacimiento')
        user_exists = (Usuario.objects.filter(username = cleaned_data.get('email')).count() > 0)

        if fecha_nacimiento:
            fecha_nacimiento = ('%s' % (fecha_nacimiento))
            fecha_nacimiento = datetime.strptime(fecha_nacimiento, "%Y-%m-%d")
            if datetime.today() <= fecha_nacimiento:
                msg = u"Por favor ingrese una fecha de nacimiento valida"
                self.add_error('fecha_nacimiento', msg)
                
        if user_exists:
            msg = u"Ya existe un usuario registrado con este correo electronico"
            self.add_error('email', msg)        
                
        return cleaned_data

    class Meta():
        model = Cliente
        fields = ('first_name', 'last_name', 'tipo_documento', 'numero_documento', 'fecha_nacimiento', 'telefono','direccion', 'email', 'password1', 'password2')


class FormularioModificarCliente(forms.ModelForm):
    def clean(self):
        cleaned_data = super(FormularioModificarCliente, self).clean()
        fecha_nacimiento = cleaned_data.get('fecha_nacimiento')
        
        if fecha_nacimiento:
            fecha_nacimiento = ('%s' % (fecha_nacimiento))
            fecha_nacimiento = datetime.strptime(fecha_nacimiento, "%Y-%m-%d")
            if datetime.today() <= fecha_nacimiento:
                msg = u"Por favor ingrese una fecha de nacimiento valida"
                self.add_error('fecha_nacimiento', msg)       
                        
        return cleaned_data
    
    class Meta():
        model = Cliente
        fields = ('first_name', 'last_name', 'fecha_nacimiento', 'telefono','direccion')

class FormularioModificarCuenta(forms.ModelForm):
    def clean(self):
        cleaned_data = super(FormularioModificarCuenta, self).clean()
        fecha_nacimiento = cleaned_data.get('fecha_nacimiento')
                
        if fecha_nacimiento:
            fecha_nacimiento = ('%s' % (fecha_nacimiento))
            fecha_nacimiento = datetime.strptime(fecha_nacimiento, "%Y-%m-%d")
            if datetime.today() <= fecha_nacimiento:
                msg = u"Por favor ingrese una fecha de nacimiento valida"
                self.add_error('fecha_nacimiento', msg)       
                                
        return cleaned_data
            
    class Meta():
        model = Usuario
        fields = ('first_name', 'last_name', 'fecha_nacimiento')

apps/clientes/views.py
from django.shortcuts import render, redirect
from .forms import FormularioModificarCliente, FormularioModificarCuenta, FormularioRegistroCliente
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout
from .models import Cliente
from ..usuarios.models import Usuario
from apps.carritos.models import Carrito
from apps.categorias.models import Categoria
from django.db.models import Q
from apps.productos.models import Producto


# Create your views here.
def registro_view(request):
    if request.method == 'POST':
        form = FormularioRegistroCliente(request.POST)
        if form.is_valid():
            instance = form.save(commit = False)
            email = form.cleaned_data.get('email')
            instance.username = email
            instance.save()
            messages.success(request, 'Cliente registrado exitosamente')
            return redirect('clientes:login')
    else:
        form = FormularioRegistroCliente()

    return render(request, 'clientes/registro.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'clientes/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')
    
def perfil_view(request, numero_documento):
    categorias = Categoria.objects.all()

    if not request.user.is_authenticated:
            carritos = None
    else:
        cliente = request.user
        carritos = Carrito.objects.filter(cliente = cliente)

    try:
        cliente = Cliente.objects.get(usuario_ptr_id=numero_documento)
    except  Cliente.DoesNotExist:
        cliente = Usuario.objects.get(numero_documento=numero_documento)

    if request.method == 'POST':
        if cliente.is_staff:
            form = FormularioModificarCuenta(request.POST, instance=cliente)
        else:
            form = FormularioModificarCliente(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cambios guardados exitosamente')
        return redirect('clientes:perfil', numero_documento)

    else:
        if cliente.is_staff:
            form = FormularioModificarCuenta(instance=cliente)
        else:
            form = FormularioModificarCliente(instance=cliente)
    
    queryset = request.GET.get("buscar")
    
    if queryset:
        productos = Producto.objects.filter(
            Q(nombre__icontains = queryset) |
            Q(descripcion__icontains = queryset)|
            Q(subcategoria__nombre__icontains = queryset) |
            Q(subcategoria__categoria__nombre__icontains = queryset)
        ).distinct()
        return render(request, 'home.html', {'productos':productos, 'categorias': categorias, 'carritos':carritos})
    else:
        return render(request, 'clientes/perfil.html', {'form':form, 'cliente': cliente, 'categorias': categorias, 'carritos':carritos})
            

def change_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Cambios guardados exitosamente')
            return redirect('clientes:login')
        else:
            return redirect('clientes:change_password')
    else:
        form = PasswordChangeForm(user= request.user)
        return render(request, 'clientes/change_password.html', {'form':form})

def eliminarCuenta_view(request, numero_documento):
    usuario = Usuario.objects.get(numero_documento=numero_documento)
    if request.method == 'GET':
        usuario.is_active = 'f'
        usuario.save()
        messages.success(request, 'Cuenta eliminada exitosamente')
        usuario = request.user
        if usuario.is_staff:
            return redirect('clientes:consulta')
        else:
            return redirect('home')

def consultarClientes_view(request):
    categorias = Categoria.objects.all()
    clientes = Cliente.objects.filter(is_staff='f', is_superuser='f')
    return render(request, 'clientes/consultar.html', {'clientes': clientes, 'categorias': categorias})

def activarCliente_view(request, numero_documento):
    usuario = Usuario.objects.get(numero_documento=numero_documento)
    if request.method == 'GET':
        usuario.is_active = 't'
        usuario.save()
        messages.success(request, 'Cuenta reactivada exitosamente')
        return redirect('clientes:consulta')

apps/clientes/templates/clientes/change_password.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>Cambiar contraseña</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'icon.png'%}"  />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="{% static 'css/AdminLTE.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="bg-black">
        

        <div class="form-box" id="login-box">
            <div class="header">Cambiar contraseña</div>
            <form method="POST">
                <div class="body bg-gray">
                    {% if messages %}
                        {% for message in messages %}
                            <div class ="alert alert-{{ message.tags }} alert-dismissable">
                                <i class="fa fa-check"></i>
                                <button type="button"class= "close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% bootstrap_form form %}
                </div>
                <div class="footer">                                                               
                    <button type="submit" class="btn bg-olive btn-block">Cambiar contraseña</button>  
                </div>
            </form>
        </div>


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>        

    </body>
</html>

apps/clientes/templates/clientes/consultar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Consultar clientes
{% endblock titulo%}

{% block titulo_contenido%}
Clientes
{% endblock titulo_contenido%}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido %}
<!--filas donde se contendran 3 widgets-->
<div class="box box-danger" style="padding: 10px">
    {% for cliente in clientes %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-md-4">
            {% if cliente.is_active %}
            <div class="box box-solid box-danger">
                <div class="box-header">
                    <h3 class="box-title">{{cliente.first_name}} {{cliente.last_name}}</h3>
                    <div class="box-tools pull-right">
                        <a data-toggle="modal" data-target="#compose-modal_{{cliente.numero_documento}}">
                            <button class="btn btn-danger btn-sm">
                                <i class="fa fa-times"></i></i>
                            </button>
                        </a>
                    </div>
                    <div class="modal fade" id="compose-modal_{{cliente.numero_documento}}" tabindex="-1" role="dialog"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"
                                        aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">¿Esta seguro que desea desactivar la cuenta de este cliente?
                                    </h4>
                                </div>

                                <div class="modal-footer clearfix">

                                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                            class="fa fa-times"></i>Cancelar</button>
                                    <a href="{% url 'clientes:eliminar-cuenta' cliente.numero_documento %}">
                                        <button type="submit" class="btn btn-primary pull-left"> Si, estoy
                                            seguro</button>
                                    </a>
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
                <div class="box-body">
                    <div class="contenido">
                        <h3 class="box-title">Información cliente</h3>

                        <div id="profile" class="tab-pane">
                            <div class="panel-body bio-graph-info">
                                <div class="row">
                                    <div class="bio-row">
                                        <h4>E-mail : {{cliente.username}}</h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>Fecha de nacimiento : {{cliente.fecha_nacimiento}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>Tipo de documento : {{cliente.tipo_documento}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>N° documento : {{cliente.numero_documento}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>N° Telefonico : {{cliente.telefono}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>Direccion : {{cliente.direccion}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <div class="box-tools pull-right">
                                            <a href="{% url 'facturas:compras' cliente.numero_documento %}">
                                                <button class="btn btn-danger btn-sm">
                                                    Historial de compras
                                                </button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">{{cliente.first_name}} {{cliente.last_name}}</h3>
                    <div class="box-tools pull-right">
                        <a href="{% url 'clientes:activar-cuenta' cliente.numero_documento %}">
                            <button class="btn  btn-sm">
                                Reactivar

                            </button>
                        </a>
                    </div>
                </div>
                <div class="box-body">
                    <div class="contenido">
                        <h3 class="box-title">Información cliente</h3>

                        <div id="profile" class="tab-pane">
                            <div class="panel-body bio-graph-info">
                                <div class="row">
                                    <div class="bio-row">
                                        <h4>E-mail : {{cliente.username}}</h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>Fecha de nacimiento : {{cliente.fecha_nacimiento}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>Tipo de documento : {{cliente.tipo_documento}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>N° documento : {{cliente.numero_documento}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>N° Telefonico : {{cliente.telefono}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <h4>Direccion : {{cliente.direccion}} </h4>
                                    </div>
                                    <div class="bio-row">
                                        <div class="box-tools pull-right">
                                            <a href="{% url 'facturas:compras' cliente.numero_documento %}">
                                                <button class="btn btn-danger btn-sm">
                                                    Historial de compras
                                                </button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
        {% if forloop.counter|divisibleby:3 %}</div>
    <div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}
    {% endfor %}
</div>
{% endblock contenido%}

apps/clientes/templates/clientes/login.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>Log in</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'icon.png'%}"  />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="{% static 'css/AdminLTE.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="bg-black">
        

        <div class="form-box" id="login-box">
            <div class="header">Iniciar Sesion</div>
            <form method="POST">
                <div class="body bg-gray">
                    {% if messages %}
                        {% for message in messages %}
                            <div class ="alert alert-{{ message.tags }} alert-dismissable">
                                <i class="fa fa-check"></i>
                                <button type="button"class= "close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% bootstrap_form form %}
                </div>
                <div class="footer">                                                               
                    <button type="submit" class="btn bg-olive btn-block">Iniciar Sesion</button>  
                    
                    <a href="{% url 'clientes:registro' %}" class="text-center">Crear una nueva cuenta</a>
                </div>
            </form>
        </div>


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>        

    </body>
</html>

apps/clientes/templates/clientes/perfil.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block titulo %}
Mi perfil
{% endblock titulo%}

{% block titulo_contenido%}
<h2 class="box-title">Mi perfil</h2>
{% endblock titulo_contenido%}

{% block carrito %}
<li class="dropdown messages-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <image src="{% static 'carrito.png'%}" heigth="20" width="20"></image>

    <span class="label label-warning">{{ carritos|length }}</span>
  </a>
  <ul class="dropdown-menu">
    <li class="header" style="color: black"><b>Tienes {{ carritos|length }} producto(s) en tu carrito</b>
    </li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        {% for carrito in carritos %}
        <li>
          <a href="{% url 'productos:consultarProducto' carrito.producto.codigo %}" style="color: black">
            <div class="pull-left">
              <img src="{{ MEDIA_URL }}{{carrito.producto.imagen}}" width="75px">
            </div>
            <h4 style="color: black">{{ carrito.producto.nombre }}</h4>
            <p id="precio" type="number">
              $ {{ carrito.producto.oferta }}
            </p>
            <p id="cantidad" type="number">
              Cantidad : {{ carrito.cantidad }}
            </p>
          </a>

        </li>
        {% endfor %}
      </ul>
    </li>
    <li class="footer"><a href="{% url 'carritos:carrito' %}" style="color: black">Ir al carrito</a></li>
  </ul>
</li>
{% endblock carrito %}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
  <a href="#">
    <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
    <i class="fa fa-angle-left pull-right"></i>
  </a>
  <ul class="treeview-menu">
    <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i class="fa fa-angle-double-right"></i>Ver
        todos</a></li>
    {% for subcategoria in categoria.subcategorias.all %}
    <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
          class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
    {% endfor %}
  </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido %}
<div class='row'>
  <div class='col-xs-12'>
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#fa-icons" data-toggle="tab">Mis datos</a></li>
        <li><a href="#glyphicons" data-toggle="tab">Editar perfil</a></li>
      </ul>
      <div class="tab-content">
        <!-- Font Awesome icons -->
        <div class="tab-pane active" id="fa-icons">
          <section id="new">
            <h4 class="page-header">Información de cuenta</h4>

            <div id="profile" class="tab-pane">
              <div class="panel-body bio-graph-info">
                <div class="row">
                  <div class="bio-row">
                    <h4>Nombre : {{user.first_name}} {{user.last_name}}</h4>
                  </div>
                  <div class="bio-row">
                    <h4>E-mail : {{user.email}}</h4>
                  </div>
                </div>
              </div>
            </div>

          </section>

          <section id="web-application">
            <h4 class="page-header">Información personal</h4>

            <div id="profile" class="tab-pane">
              <div class="panel-body bio-graph-info">
                <div class="row">
                  <div class="bio-row">
                    <h4>Fecha de nacimiento : {{user.fecha_nacimiento}} </h4>
                  </div>
                  <div class="bio-row">
                    <h4>Tipo de documento : {{user.tipo_documento}} </h4>
                  </div>
                  <div class="bio-row">
                    <h4>N° documento : {{user.numero_documento}} </h4>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {% if not user.is_staff %}
          <section id="form-control">
            <h4 class="page-header">Información cliente</h4>

            <div id="profile" class="tab-pane">
              <div class="panel-body bio-graph-info">
                <div class="row">
                  <div class="bio-row">
                    <h4>N° telefonico : {{cliente.telefono}} </h4>
                  </div>
                  <div class="bio-row">
                    <h4>Direccion : {{cliente.direccion}} </h4>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {% endif %}

        </div><!-- /#fa-icons -->
        <!-- glyphicons-->
        <div class="tab-pane" id="glyphicons">
          <form method="POST">
            <div>
              {% csrf_token %}
              {% bootstrap_form form %}
            </div>
            <div>
              <button class="btn btn-primary" type="submit">Guardar cambios</button>
              <a class="btn btn-info" href="{% url 'clientes:change_password' %}">Cambiar contraseña</a>
              {% if not user.is_staff %}
              <a class="btn btn-danger" data-toggle="modal" data-target="#compose-modal">
                Eliminar cuenta
              </a>
              {% endif %}

            </div>
            <div class="modal fade" id="compose-modal" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">¿Esta seguro que desea eliminar su cuenta?</h4>
                  </div>

                  <div class="modal-footer clearfix">

                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                        class="fa fa-times"></i>Cancelar</button>
                    <a class="btn btn-primary pull-left"
                      href="{% url 'clientes:eliminar-cuenta' user.numero_documento %}">
                      Si, estoy seguro
                    </a>
                  </div>

                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

          </form>
        </div><!-- /#ion-icons -->

      </div><!-- /.tab-content -->
    </div><!-- /.nav-tabs-custom -->
  </div><!-- /.col -->
</div><!-- /.row -->

{% endblock contenido %}