apps/categorias/urls.py
from django.urls import path
from apps.categorias.views import *

app_name = 'categorias'

urlpatterns=[
    path('crear_categoria/', crear_categoria_view, name = 'crear_categoria'),
    path('consultar_categoria/', consultar_categorias_view, name = 'consultar_categorias'),
    path('eliminar_categoria/<int:id>', eliminar_categoria_view, name = 'eliminar_categoria'),
    path('modificar_categoria/<int:id>', modificar_categoria_view, name = 'modificar_categoria'),
]

apps/productos/urls.py
from django.urls import path
from .views import *

app_name = 'productos'

urlpatterns=[
    path('registrar/', registrar_view, name = 'registrar'),
    path('consultar/', consultarProdutos_view, name = 'consultar'),
    path('subcategoria/<int:subcategoria_id>', consultarPorSubcategoria_view, name = 'consultarPorSubcategoria'),
    path('categoria/<int:categoria_id>', consultarPorCategoria_view, name = 'consultarPorCategoria'),
    path('producto/<str:codigo>', consultarProducto_view, name = 'consultarProducto'),
    path('modificar/<str:codigo>', modificarProductos_view, name = 'modificar'),
    path('eliminar/<str:codigo>', eliminarProducto_view, name = 'eliminar'),
    path('detalle/<int:id>', eliminarDetalle_view, name = 'eliminar_detalle'),
    path('descuentos/', productosDescuento_view, name = 'descuentos'),
]

apps/subcategorias/urls.py
from django.urls import path
from apps.subcategorias.views import *

app_name = 'subcategorias'

urlpatterns=[
    path('crear_subcategoria/', crear_subcategoria_view, name = 'crear_subcategoria'),
    path('modificar_subcategoria/<int:id>', modificar_subcategoria_view, name = 'modificar_subcategoria'),
    path('eliminar_subcategoria/<int:id>', eliminar_subcategoria_view, name = 'eliminar_subcategoria'),
]

madlab/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.pages import views

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cliente/', include('apps.clientes.urls', namespace = 'clientes')),
    path('gerente/', include('apps.usuarios.urls', namespace = 'gerentes')),
    path('productos/', include('apps.productos.urls', namespace='productos')),
    path('categorias/', include('apps.categorias.urls', namespace='categorias')),
    path('subcategorias/', include('apps.subcategorias.urls', namespace='subcategorias')),
    path('almacenes/', include('apps.almacenes.urls', namespace='almacenes')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('descuentos/', include('apps.descuentos.urls', namespace = 'descuentos')),
    path('carritos/', include('apps.carritos.urls', namespace = 'carritos')),
    path('reportes/', include('apps.reportes.urls', namespace = 'reportes')),
    path('facturas/', include('apps.facturas.urls', namespace = 'facturas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/categorias/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length = 30)

    def __str__(self):
        return self.nombre

apps/categorias/forms.py
from django import forms
from .models import Categoria

class FormularioCreacionCategoria(forms.ModelForm):
    class Meta():
        model = Categoria
        fields = ('nombre',)

apps/categorias/views.py
from django.shortcuts import render, redirect
from .forms import FormularioCreacionCategoria
from django.contrib import messages
from .models import Categoria

# Create your views here.
def crear_categoria_view(request):
    categorias = Categoria.objects.all()
    if request.method == 'POST':
        form = FormularioCreacionCategoria(request.POST)
        if form.is_valid():
            instance = form.save()
            messages.success(request, 'Categoria registrada exitosamente')
            redirect('categorias:crear_categoria')
    else:
        form = FormularioCreacionCategoria()

    return render(request, 'categorias/registro.html', {'form': form, 'categorias': categorias})


def consultar_categorias_view(request):
    categorias = Categoria.objects.all()
    return render(request, 'categorias/consultar.html', {'categorias': categorias})


def eliminar_categoria_view(request, id):
    categorias = Categoria.objects.all()
    Categoria.objects.filter(id=id).delete()
    messages.success(request, 'Categoria eliminada exitosamente')
    return redirect('categorias:consultar_categorias')


def modificar_categoria_view(request, id):
    categorias = Categoria.objects.all()
    categoria = Categoria.objects.get(id = id)
    if request.method == 'GET':
        form = FormularioCreacionCategoria(instance = categoria)
    else:
        form = FormularioCreacionCategoria(request.POST, instance = categoria)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria modificada exitosamente')
        return redirect('categorias:consultar_categorias')

    return render(request, 'categorias/modificar.html', {'form': form, 'categorias': categorias})

apps/categorias/templates/categorias/consultar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Consultar categorias
{% endblock titulo %}

{% block titulo_contenido%}
Categorias
{% endblock titulo_contenido%}

{% block ciudad %}
<h5>Usted está en BOGOTA</h5>
<div class="btn-group">
    <button type="button" class="btn btn-default">Action</button>
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
    </ul>
</div>
{% endblock ciudad %}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido %}
<!--filas donde se contendran 3 widgets-->
<div class="box box-danger" style="padding: 10px">
    {% for categoria in categorias %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-md-4">
            <div class="box box-solid box-danger">
                <div class="box-header">
                    <h3 class="box-title">{{categoria.nombre}}</h3>
                    <div class="box-tools pull-right">
                        <a href="{% url 'categorias:modificar_categoria' categoria.id %}">
                            <button class="btn btn-danger btn-sm"><i class="fa fa-pencil"></i></button>
                        </a>
                        <a data-toggle="modal" data-target="#compose-modal1_{{categoria.id}}">
                            <button class="btn btn-danger btn-sm">
                                <i class="fa fa-times"></i></i>
                            </button>
                        </a>
                    </div>
                    <div class="modal fade" id="compose-modal1_{{categoria.id}}" tabindex="-1" role="dialog"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"
                                        aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">¿Esta seguro que desea eliminar esta categoria?</h4>
                                </div>

                                <div class="modal-footer clearfix">

                                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                            class="fa fa-times"></i>Cancelar</button>
                                    <a href="{% url 'categorias:eliminar_categoria' categoria.id %}">
                                        <button type="submit" class="btn btn-primary pull-left"> Si, estoy
                                            seguro</button>
                                    </a>
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
                <div class="box-body">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Subcategorias</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body no-padding">
                            <table class="table table-striped">
                                <tr>
                                    <th style="width: 10px">id</th>
                                    <th>Nombre</th>
                                    <th>Acciones</th>
                                </tr>
                                {% for subcategoria in categoria.subcategorias.all %}
                                <tr>
                                    <td>{{ subcategoria.id }}</td>
                                    <td>{{ subcategoria.nombre }}</td>

                                    <td>
                                        <!--Boton subcategoria-->
                                        <a href="{% url 'subcategorias:modificar_subcategoria' subcategoria.id %}">
                                            <button class="btn btn-danger btn-sm"><i class="fa fa-pencil"></i></button>
                                        </a>
                                        <!--Boton eliminar-->
                                        <a data-toggle="modal" data-target="#compose-modal_{{subcategoria.id}}">
                                            <button class="btn btn-danger btn-sm">
                                                <i class="fa fa-times"></i></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                                <div class="modal fade" id="compose-modal_{{subcategoria.id}}" tabindex="-1"
                                    role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-hidden="true">&times;</button>
                                                <h4 class="modal-title">¿Esta seguro que desea eliminar esta
                                                    subcategoria?</h4>
                                            </div>

                                            <div class="modal-footer clearfix">

                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i
                                                        class="fa fa-times"></i>Cancelar</button>
                                                <a
                                                    href="{% url 'subcategorias:eliminar_subcategoria' subcategoria.id %}">
                                                    <button type="submit" class="btn btn-primary pull-left"> Si,
                                                        estoy
                                                        seguro</button>
                                                </a>
                                            </div>

                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->
                                {% endfor %}

                            </table>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            <!--widgets-->
        </div>
        {% if forloop.counter|divisibleby:3 %}</div>
    <div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}

    {% endfor %}
</div>

<!--filas-->

<!--widget-->
{% endblock contenido%}

apps/categorias/templates/categorias/modificar.html
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block titulo %}
Modificar Categoria
{% endblock titulo%}

{% block titulo_contenido%}
Modificar Categoria
{% endblock titulo_contenido%}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="#"><i class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido%}
<div class="box box-danger" style="padding: 10px">
    <form method="POST">
        <div>
            {% csrf_token %}
            {% bootstrap_form form %}
        </div>
        <div>
            <button type="submit">Modificar</button>
        </div>
    </form>
</div>
{% endblock contenido%}

apps/categorias/templates/categorias/registro.html
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block titulo %}
Registrar categoria
{% endblock titulo%}

{% block titulo_contenido%}
Registrar categoria
{% endblock titulo_contenido%}

{% block barra %}
{% for categoria in categorias %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-bookmark"></i> <span>{{ categoria.nombre }}</span>
        <i class="fa fa-angle-left pull-right"></i>
    </a>
    <ul class="treeview-menu">
        <li><a href="{% url 'productos:consultarPorCategoria' categoria.id %}"><i
                    class="fa fa-angle-double-right"></i>Ver todos</a></li>
        {% for subcategoria in categoria.subcategorias.all %}
        <li><a href="{% url 'productos:consultarPorSubcategoria' subcategoria.id %}"><i
                    class="fa fa-angle-double-right"></i>{{ subcategoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
{% endblock barra %}

{% block contenido%}
<div class="box box-danger" style="padding: 10px">
    <form method="POST">
        <div>
            {% csrf_token %}
            {% bootstrap_form form %}
        </div>
        <div>
            <button type="submit">Agregar</button>
        </div>
    </form>
</div>
{% endblock contenido%}